name: Build all samples
on: [pull_request]
jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Set up JDK 21"
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: "run test"
        working-directory: ./junit5-jupiter-extensions
        run: ./gradlew check
